name: Cypress API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npm run test

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/final

      - name: Upload evidence (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-evidence
          path: docs/evidence/
          if-no-files-found: ignore
